name: Run the integration tests

on:
  push:
    # branches:
    #     - develop_branch

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: 2206669
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm ci

      # Run tests
      - run: npm test
