name: Run the integration tests

on:
  push:
    # branches:
    #     -feature-branch

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm ci

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "PORT=3000" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=" >> .env
          echo "DB_DATABASE=share-a-meal-programmeren-4" >> .env

      # Run tests
      - run: npm test
