name: Run the integration tests

on:
  push:
    # branches:
    #     -feature-branch

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "mysecretpassword"
          MYSQL_DATABASE: share-a-meal-programmeren-4
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - run: npm ci
    
      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "PORT=3000" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=mysecretpassword" >> .env
          echo "DB_DATABASE=share-a-meal-programmeren-4" >> .env

      # Run tests
      - run: npm test
